import { Ebook } from "../shared/types";

export const ebooks: Ebook[] = [
  {
    id: 1,
    category: "fiction",
    title: "The Time Traveler's Tale",
    author: "John Doe",
    description: "A thrilling story about a man who travels through time.",
    description_zh: "一个关于穿越时空的男人的惊险故事。",
    published: true,
    rating: 4.5,
  },
  {
    id: 2,
    category: "non-fiction",
    title: "Mastering AWS",
    author: "Jane Smith",
    description: "Comprehensive guide to using AWS services.",
    description_zh: "使用 AWS 服务的综合指南。",
    published: true,
    rating: 4.8,
  },
  {
    id: 3,
    category: "fiction",
    title: "The Last Kingdom",
    author: "Robert Drake",
    description: "A tale of warriors, betrayal, and destiny in an ancient land.",
    description_zh: "一个关于战士、背叛与命运的古代传说。",
    published: true,
    rating: 4.1,
  },
  {
    id: 4,
    category: "technology",
    title: "JavaScript Deep Dive",
    author: "Lena Yu",
    description: "Explore advanced concepts in modern JavaScript development.",
    description_zh: "深入探索现代 JavaScript 开发中的高级概念。",
    published: true,
    rating: 4.7,
  },
  {
    id: 5,
    category: "technology",
    title: "Understanding TypeScript",
    author: "Max Müller",
    description: "A beginner-friendly guide to TypeScript and how it works with JavaScript.",
    description_zh: "TypeScript 与 JavaScript 配合使用的入门指南。",
    published: false,
    rating: 4.3,
  },
  {
    id: 6,
    category: "history",
    title: "The Rise and Fall of Empires",
    author: "Clara Bennett",
    description: "A historical overview of the world's greatest empires.",
    description_zh: "对世界伟大帝国兴衰的历史回顾。",
    published: true,
    rating: 4.6,
  },
  {
    id: 7,
    category: "non-fiction",
    title: "Minimalism in Life",
    author: "Alex Johnson",
    description: "Discover how to live with less and find happiness.",
    description_zh: "探索如何以更少的物质生活并获得幸福。",
    published: true,
    rating: 3.9,
  },
  {
    id: 8,
    category: "fiction",
    title: "Into the Silent Forest",
    author: "Nina Hart",
    description: "A suspenseful journey through a mysterious forest where nothing is what it seems.",
    description_zh: "一段穿越神秘森林的悬疑之旅，一切都出乎意料。",
    published: false,
    rating: 4.2,
  },
  {
    id: 9,
    category: "science",
    title: "Quantum Physics Explained",
    author: "Dr. Kevin Lee",
    description: "Breakdown of the complex world of quantum mechanics in simple terms.",
    description_zh: "用简单的语言解释复杂的量子力学世界。",
    published: true,
    rating: 4.9,
  },
  {
    id: 10,
    category: "fiction",
    title: "Moonlight Shadows",
    author: "Ella Ray",
    description: "A poetic and emotional tale of love, loss, and redemption under the stars.",
    description_zh: "在星空下关于爱、失落与救赎的诗意故事。",
    published: true,
    rating: 4.4,
  },
];
