import { Ebook } from "../shared/types";

export const ebooks: Ebook[] = [
  {
    id: 1,
    category: "fiction",
    title: "The Time Traveler's Tale",
    author: "John Doe",
    description: "A thrilling story about a man who travels through time.",
    published: true,
    rating: 4.5,
  },
  {
    id: 2,
    category: "non-fiction",
    title: "Mastering AWS",
    author: "Jane Smith",
    description: "Comprehensive guide to using AWS services.",
    published: true,
    rating: 4.8,
  },
  {
    id: 3,
    category: "fiction",
    title: "The Last Kingdom",
    author: "Robert Drake",
    description: "A tale of warriors, betrayal, and destiny in an ancient land.",
    published: true,
    rating: 4.1,
  },
  {
    id: 4,
    category: "technology",
    title: "JavaScript Deep Dive",
    author: "Lena Yu",
    description: "Explore advanced concepts in modern JavaScript development.",
    published: true,
    rating: 4.7,
  },
  {
    id: 5,
    category: "technology",
    title: "Understanding TypeScript",
    author: "Max Müller",
    description: "A beginner-friendly guide to TypeScript and how it works with JavaScript.",
    published: false,
    rating: 4.3,
  },
  {
    id: 6,
    category: "history",
    title: "The Rise and Fall of Empires",
    author: "Clara Bennett",
    description: "A historical overview of the world's greatest empires.",
    published: true,
    rating: 4.6,
  },
  {
    id: 7,
    category: "non-fiction",
    title: "Minimalism in Life",
    author: "Alex Johnson",
    description: "Discover how to live with less and find happiness.",
    published: true,
    rating: 3.9,
  },
  {
    id: 8,
    category: "fiction",
    title: "Into the Silent Forest",
    author: "Nina Hart",
    description: "A suspenseful journey through a mysterious forest where nothing is what it seems.",
    published: false,
    rating: 4.2,
  },
  {
    id: 9,
    category: "science",
    title: "Quantum Physics Explained",
    author: "Dr. Kevin Lee",
    description: "Breakdown of the complex world of quantum mechanics in simple terms.",
    published: true,
    rating: 4.9,
  },
  {
    id: 10,
    category: "fiction",
    title: "Moonlight Shadows",
    author: "Ella Ray",
    description: "A poetic and emotional tale of love, loss, and redemption under the stars.",
    published: true,
    rating: 4.4,
  },
];
